"""添加is_admin_user字段

Revision ID: 1a3591485131
Revises: 2e6d09a87c5f
Create Date: 2025-03-25 13:45:58.267856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3591485131'
down_revision = '2e6d09a87c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 注释掉对不存在的临时表的操作
    # op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin_user', sa.Boolean(), server_default='0', nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_is_admin_user'), ['is_admin_user'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_admin_user'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_column('is_admin_user')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # 注释掉对不存在的临时表的操作
    # op.create_table('_alembic_tmp_users',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    # sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    # sa.Column('nickname', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('avatar', sa.VARCHAR(length=200), nullable=True),
    # sa.Column('bio', sa.TEXT(), nullable=True),
    # sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    # sa.Column('created_at', sa.DATETIME(), nullable=False),
    # sa.Column('updated_at', sa.DATETIME(), nullable=False),
    # sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email', name='uq_user_email'),
    # sa.UniqueConstraint('username', name='uq_user_username')
    # )
    # ### end Alembic commands ###
