"""add user sessions table

Revision ID: 9c4b6e01a477
Revises: 420a050122ea
Create Date: 2025-02-25 15:34:43.361825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4b6e01a477'
down_revision = '420a050122ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('target_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=50), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('action')

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activity', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('last_activity')

    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('ip_address')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_type')
        batch_op.drop_column('operation')

    # ### end Alembic commands ###
